<?php
/**
* Implements hook_help() to the module.
* 
*/
function ytvideobg_help($path, $arg){
	switch ($path){
		case 'admin/help#video_blog':{
			$ret_val = '<h3>' . t('About YouTube Video Background') . '</h3>';
			$ret_val = '<p>' . t('Here is discription of the Module which You can Translate') . '</p>';
			return $ret_val;
			break;
		}
	}
}
/**
 * Implements hook_permission().
 */
function ytvideobg_permission() {
  return array(
    'administer YouTube Video Background' => array(
      'title' => t('Administer YouTube Video Background'),
      'description' => t('Perform administrative tasks on Youtube Video Background functionality'),
    ),
  );
}
/**
 * Implements hook_menu().
 */
function ytvideobg_menu() {
  $items = array();

  // Admin configuration group.
  $items['admin/config/ytvideobg'] = array(
    'title' => 'YouTube Background',
    'description' => 'Administer YouTube Background',
    'access arguments' => array('administer youtube background'),
  );

  // Admin configuration - Settings.
  $items['admin/config/ytvideobg/manage'] = array(
    'title' => 'YouTube Background settings',
    'description' => 'Manage YouTube Background settings and configurations.',
    'access arguments' => array('administer youtube background'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ytvideobg_admin_settings_form'),
  );

  return $items;
}
/**
 * Implements hook_form().
 */
function ytvideobg_admin_settings_form($node, &$form_state) {
  $form = array();

  $form['overview'] = array(
    '#markup' => t('This interface allows administrators to manage general YouTube Video Background Settings'),
    '#prefix' => '<p>',
    '#suffix' => '</p>',
  );


  $form['ytvideobg_default_video_url'] = array(
    '#title' => t('Video URL'),
    '#description' => t('Full video URL. IMPORTANT: without "http://".'),
    '#type' => 'textfield',
    '#default_value' => variable_get('ytvideobg_default_video_url', 'www.youtube.com/watch?v=_nCaWJ2j-0M'),
    '#required' => TRUE,
  );
  
  $form['ytvideobg_default_title_text'] = array(
    '#title' => t('Title Text'),
    '#description' => t('Add here H3 title text'),
    '#type' => 'textfield',
    '#default_value' => variable_get('ytvideobg_default_title_text', 'Add any text here'),
    '#required' => TRUE,
  );
  
  $form['ytvideobg_default_description_text'] = array(
    '#title' => t('Description Text'),
    '#description' => t('Add short description text'),
    '#type' => 'textfield',
    '#default_value' => variable_get('ytvideobg_default_description_text', 'Add any text here'),
    '#required' => TRUE,
  );


  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  return $form;
}

/**
 * Process a validated admin setting submission.
 */
function ytvideobg_admin_settings_form_submit($form, &$form_state) {
  // Rebuild the form.
  $form_state['rebuild'] = TRUE;

  // Save setting variables.
  variable_set('ytvideobg_default_video_url', $form_state['values']['ytvideobg_default_video_url']);
  variable_set('ytvideobg_default_description_text', $form_state['values']['ytvideobg_default_description_text']);
  variable_set('ytvideobg_default_title_text', $form_state['values']['ytvideobg_default_title_text']);

  // Notify user.
  drupal_set_message(t('Your Video Background settings has been saved.'));
}
/**
 * Implements hook_block_info().
 */
function ytvideobg_block_info() {
  $blocks = array();
  $blocks['youtube_block'] = array(
    'info' => t('YouTube Video Block'),
  );
  return $blocks;
}
/**
 * Implements hook_block_view().
 */
function ytvideobg_block_view($delta='') {
  $block = array();
  
  switch($delta) {
    case 'youtube_block' :
      $block['content'] = my_block_view();
      break;
  }
  
  return $block;
}

/**
 * Custom function to assemble renderable array for block content.
 * Returns a renderable array with the block content.
 * @return
 *   returns a renderable array of block content.
 */
function my_block_view() {
	
	
	return $output;
}
