<?php
/**
* Implements hook_help() to the module.
* 
*/
function ytvideobg_help($path, $arg){
	switch ($path){
		case 'admin/help#video_blog':{
			$ret_val = '<h3>' . t('About YouTube Video Background') . '</h3>';
			$ret_val = '<p>' . t('Here is discription of the Module which You can Translate') . '</p>';
			return $ret_val;
			break;
		}
	}
}
/**
 * Implements hook_permission().
 */
function ytvideobg_permission() {
  return array(
    'administer YouTube Video Background' => array(
      'title' => t('Administer YouTube Video Background'),
      'description' => t('Perform administrative tasks on Youtube Video Background functionality'),
    ),
  );
}